### PR TITLE
Donation page UI updated

### PR DESCRIPTION
**Pull request by DugarRishab**
## Description: 
- This PR closes issue #7 
- A new Image (.png) was added and used in the donations page
- The screenshot given below shows the updated UI.

image

## Related Issues:
- The "Razor Pay" button cannot be customized much because it is loaded dynamically.

### CODE REVIEW

**Comment by DugarRishab** [comment]
For any PR to be accepted, it needs the label - `hacktoberfest-accepted`.

**Comment by DugarRishab** [comment]
Hey @ShrutiMishra-2002 and @mdnazisharman2803 this repo was just excluded from hacktoberfest. Any idea why?

**Comment by ShrutiMishra-2002** [comment]
@DugarRishab from where did you see this ???

**Comment by DugarRishab** [comment]
> @DugarRishab from where did you see this ??? i.e the project is excluded because I haven't received any mail regarding this

I saw this on my hacktoberfest page. They say that this repo has not valued the community guidelines and so is excluded from Hacktoberfest.

**Pull request merged**
