### PR TITLE
Uifixes

### PR DESCRIPTION
**Pull request by khattarmanali**
ISSUE:TRANSOPEDIA HIGHLIGHTS SECTION CARDS HEIGHT FIXED

### CODE REVIEW

**Comment by ShrutiMishra-2002** [comment]
@khattarmanali please add the screenshots

**Comment by khattarmanali** [comment]
Before:

q

After:

image

**Comment by ShrutiMishra-2002** [comment]
@khattarmanali can you please explain why you deleted the queries and then added the same queries again ?!

**Comment by khattarmanali** [comment]
In my last commit I only fixed the height of the card but today when I open this page for a screenshot I saw that buttons are not aligned according to the height of the card so I fixed all the things and created an another request

**Comment by ShrutiMishra-2002** [comment]
@khattarmanali this work is already done (Card of testimonal Section aligned !! #25)

**Pull request closed without merging**
