### PR TITLE
Card of testimonal Section aligned !!

### PR DESCRIPTION
**Pull request by ranjeet25**
## Before :

image

## After:

image
image

### CODE REVIEW

**Comment by ranjeet25** [comment]
@ShrutiMishra-2002 can you please review my PR !!

**Comment by ShrutiMishra-2002** [comment]
@ranjeet25 great work but you can improve it further by making all the blue text in one line

**Comment by ranjeet25** [comment]
@ShrutiMishra-2002 OK !!

**Comment by ranjeet25** [comment]
Hey @ShrutiMishra-2002  I have  made the changes, You can have a look !!

> ## Before :
> image
> 
> ## After:
> image image

After modification :

image

**Comment by ranjeet25** [comment]
Hey @ShrutiMishra-2002 I have made the changes Have a Look !!

**Pull request merged**
