### PR TITLE
Made Donation Page Responsive

### LINKED ISSUE #5: Make Donation Page Responsive
- Visit the link to check the details of the page to be worked on https://shrutimishra-2002.github.io/Transopedia-website/storeanddonate/donation.html

### PR DESCRIPTION
**Pull request by aksha123-git**
- Fixes #5
- I made  the Donation Page responsive by adding Media Queries
- Adding screenshots for different dimensions

### CODE REVIEW

**Comment by ShrutiMishra-2002** [comment]
The 2nd screenshot is not responsive @aksha123-git please add another screenshot or make the required changes

**Comment by ShrutiMishra-2002** [comment]
@aksha123-git please make the changes as soon as possible if not possible please inform so that I can assign this issue to other person

**Comment by aksha123-git** [comment]
I made changes please check it

**Comment by aksha123-git** [comment]
I made changes please check it @ShrutiMishra-2002

**Review by ShrutiMishra-2002 — APPROVED** [review]

**Pull request merged**
