### PR TITLE
Fixes #23 : Styled the Feedback form

### LINKED ISSUE #23: Style the Feedback Page

### PR DESCRIPTION
**Pull request by palashb01**
### Description :

- Fixed the feedback form styling

**ScreenShots:**

hack

### CODE REVIEW

**Comment by palashb01** [comment]
Hey @ShrutiMishra-2002 , Please review this PR and assign Hacktoberfest-accepted label, Thanks.

**Comment by ShrutiMishra-2002** [comment]
@palashb01 this is not matching the website theme kindly make the required changes

**Comment by palashb01** [comment]
@ShrutiMishra-2002 got it, Working on it.

**Comment by palashb01** [comment]
Hey @ShrutiMishra-2002 , Please review this PR and assign Hacktoberfest-accepted label, Thanks.

**Comment by ShrutiMishra-2002** [comment]
@palashb01 it is still not looking up to the mark

**Comment by palashb01** [comment]
Hey @ShrutiMishra-2002, Could you Please the design or your idea, how the feedback page should be styled, Thanks.

**Pull request closed without merging**
