### PR TITLE
'changes_made_to_about_us.html'

### PR DESCRIPTION
**Pull request by KGoutham7214**
Made changes to about_us.html added in-line CSS styling and a background image 

#issue36

### CODE REVIEW

**Comment by ShrutiMishra-2002** [comment]
@KGoutham7214 add screenshot

**Comment by KGoutham7214** [comment]
image1
ttps://user-images.githubusercontent.com/80199829/195920556-c3bb0a34-e2f9-46e1-a848-b5b124f340bd.png)

**Comment by KGoutham7214** [comment]
images are attached for reference
[image.pdf](https://github.com/ShrutiMishra-2002/hacktoberfest22_transopedia/files/9789393/image.pdf)

**Comment by ShrutiMishra-2002** [comment]
Not up to the mark

**Comment by KGoutham7214** [comment]
Could have mentioned the changes needed instead of closing 

Well thanks

**Comment by KGoutham7214** [comment]
Could have mentioned the changes needed instead of closing 

Well thanks

**Pull request closed without merging**
